# Configuration file to generate test-ui via kickoff
# kickoff -a test-react-component.yml -f ~/topics/monitoring-react-component/ -d test-react-component
package_name: test-react-component
package_description: A react component
author_full_name: Test Author
author_email: testauthor@gmail.com
author_github_account: testauthor
